export const defaultProductItem = {
  fdApplyCount: 0,
  fdApplySupplyPrice: 0,
  fdAvailableStock: 0,
  fdCurrentSupplyPrice: 0,
  fdDiscount: 100,
  fdMachineType: '1',
  fdMainId: '',
  fdProductCode: '',
  fdProductLineCode: '',
  fdProductLineName: '',
  fdProductName: '',
  fdProductSourceId: '',
  fdProductSourceNo: '',
  fdProductSourceType: '',
  fdSalePrice: 0,
  fdSettleAmount: 0,
  fdSplitMainId: '',
  fdTaxRate: 13,
  fdWarehouseCode: '',
  fdWarehouseName: '',
};
