export const USER_GETTERS_USER = 'USER_GETTERS_USER';
export const USER_GETTERS_USERINFO = 'USER_GETTERS_USERINFO';
export const USER_MUTATIONS_SET_USER = 'USER_MUTATIONS_SET_USER';
export const USER_MUTATIONS_SET_USERINFO = 'USER_MUTATIONS_SET_USERINFO';
export const USER_ACTIONS_FETCH_USER = 'USER_ACTIONS_FETCH_USER';

export const LOADING_GETTERS_LOADING = 'LOADING_GETTERS_LOADING';
export const LOADING_MUTATIONS_SET_LOADING = 'LOADING_MUTATIONS_SET_LOADING';

export const AUTH_GETTERS_TOKEN = 'AUTH_GETTERS_TOKEN';
export const AUTH_MUTATIONS_SET_TOKEN = 'AUTH_MUTATIONS_SET_TOKEN';
export const AUTH_GETTERS_MENUS = 'AUTH_GETTERS_MENUS';
export const AUTH_MUTATIONS_SET_MENUS = 'AUTH_MUTATIONS_SET_MENUS';
export const AUTH_ACTIONS_FETCH_MENUS = 'AUTH_ACTIONS_FETCH_MENUS';

export const DIRECTION_GETTERS_DIRECTION = 'DIRECTION_GETTERS_DIRECTION';
export const DIRECTION_MUTATIONS_SET_DIRECTION =
  'DIRECTION_MUTATIONS_SET_DIRECTION';

export const MENU_GETTERS_MENUS = 'MENU_GETTERS_MENUS';
export const MENU_GETTERS_MENUSMAP = 'MENU_GETTERS_MENUSMAP';
export const MENU_MUTATIONS_SET_MENUS = 'MENU_MUTATIONS_SET_MENUS';
export const MENU_ACTIONS_FETCH_MENUS = 'MENU_ACTIONS_FETCH_MENUS';

export const DEBUG_GETTERS_DEBUG = 'DEBUG_GETTERS_DEBUG';
export const DEBUG_MUTATIONS_SET_DEBUG = 'DEBUG_MUTATIONS_SET_DEBUG';
